-- =========================================================
-- STUDY LAB — CHAT SETUP MOVED
--
-- This older chat-only script has been superseded.
-- Use the unified setup instead:
--
--   supabase/studylab_backend_setup.sql
--
-- That script configures the student account, profile,
-- favorites, study progress, and temporary chat together.
-- =========================================================
